### ISSUE TITLE
Can only pull up drawer in small steps

### ISSUE THREAD

**Issue by tanjunior** [toniantunovi/ion-bottom-drawer#1]
Hello Toni,

Thanks for sharing this wonderful custom component. I am really grateful as I have been looking for something like this for quite a while.

I tried implementing it in my current project but It seems like it's not working properly.

![1534758483668](https://user-images.githubusercontent.com/11617693/44349149-ec54d180-a4ce-11e8-8d48-dabd333b5cf3.gif)

**Comment by toniantunovi** [comment]
Hi, I'll check it and get back to you soon.

**Comment by toniantunovi** [comment]
I think this problem is fixed now. You can check it

**Comment by tanjunior** [comment]
verified fixed!
