### ISSUE TITLE
Suggestion: change property to "transform" instead of "top" for improved performance.

### ISSUE THREAD

**Issue by torsorensen** [toniantunovi/ion-bottom-drawer#2]
Hi, nice and simple.
Is there a reason why you're not using "transform: translateY" instead of "top"? With transform you're not recalculating the DOM and thus it should be better for performance.

**Comment by toniantunovi** [comment]
Hi. Thanks for this great suggestion. I'll try to find time and update the code by the end of the week.

**Comment by torsorensen** [comment]
No problem :) 
It's a very straightforward edit (search/replace) and improved performance quite a bit for me when  running on actual devices using ionic3 and a modified joshmorony's drawer (very identical to yours).

On thing to note is that with transform, you would need to use this.element.nativeElement.getBoundingClientRect().top; to get the offset of the drawer.

**Comment by toniantunovi** [comment]
Hi, I've implemented suggested improvement so I'm closing the issue.
