### ISSUE TITLE
Setting initial state of the drawer 

### ISSUE THREAD

**Issue by hb1998** [toniantunovi/ion-bottom-drawer#21]
How to set initial state of the drawer, I saw the documentation it said that [(state)] = drawerState. What are the potentials value for drawerState? Is it a string or a object and if I don't set it to anything initially it is in top

**Comment by hb1998** [comment]
Found it. didn't knw it was an enum .
`drawerState:DrawerState = 0;`
possible values are :
0,1 and 2 
where 
    Bottom = 0,
    Docked = 1,
    Top = 2

**Comment by TravBradfield** [comment]
When I set 1, 2 or 3 in the [(state)] field I get an error: <ion-bottom-drawer [ERROR ->][(state)]="1" [minimumHeight]="10" [dockedHeight]="10">
    <div class="drawer-content">
      Bottom"): ng:///Map2PageModule/Map2Page.html@27:19
Parser Error: Unexpected token '=' at column 2 in [1=$event] in ng:///Map2PageModule/Map2Page.html@27:19 ("
</ion-content>


But, when I use the words 'Docked' or 'Top' I get no errors... But it. makes no difference, the tray is always open to the top of the screen
