### ISSUE TITLE
Can you add click to open and click to close support?

### ISSUE THREAD

**Issue by kzsense** [toniantunovi/ion-bottom-drawer#3]
Hey Toni, can you add click to open and click to lose support please?
Or can you give me the instructions how to do it?

**Comment by toniantunovi** [comment]
Hi,

I'm not sure what you mean by that. You can toggle the drawer by changing the value of hidden input:

`hidden: boolean - When set to false it will close the drawer completely. When set to true it will open it to docked position.`

If this is not what you needed, can you please explain a bit better what do you mean by click to open and click to close.

**Comment by kzsense** [comment]
Sorry to make u confused. The hidden input takes care of "show" or "hide" the drawer, i get it. What I mean by "click" support is when you drag the whole drawer up, I would like a "click/tap" to slide up the drawer. It would be better if you have both "click" and "drag" both.

**Comment by torsorensen** [comment]
Kzsense, why don't you just make the click listener of a button or parts of the drawer content toggle the hidden value true/false?

**Comment by toniantunovi** [comment]
Hi, you can check it now. If that's what you needed. You can now basically control the state input to change between Closed, Docked and Opened.

**Comment by bhandaribhumin** [comment]
@kzsense can you share me some example or code [.scss/.ts] because I try to achieve the same functionality. if possible thanks, brother.
