### ISSUE TITLE
After drag to bottom this drawer its gone and hide from screen.

### ISSUE THREAD

**Issue by m-saifuddin** [toniantunovi/ion-bottom-drawer#5]
Firstly, Good job done.

Overall looks good to me but drawer hide itself from screen when drag to bottom.
1. The drawer should stop at some point instead of hide from screen. so my question is how to fix the minimum height to stay drawer on screen.

**Comment by toniantunovi** [comment]
I've added the minimumHeight attribute which is calculated from the bottom of the screen. Also, you can not drag it bellow this point.

**Comment by m-saifuddin** [comment]
Thanks, @toniantunovi for this support.

**Comment by martinpring** [comment]
I know this issue is closed but wanted to add one thing. The drawer still hide itself from screen when drag to bottom if you set `shouldBounce = true`.
